spring:
  application:
    name: hakaton-rambam-patients-service
server:
  port: 9022
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:9000/eureka
  instance:
      preferIpAddress: true