spring:
  application:
    name: hakaton-rambam-departments-service
server:
  port: 9023
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:9000/eureka
  instance:
      preferIpAddress: true