spring:
  application:
    name: hakaton-rambam-gateway-service
server:
  port: 9020
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:9000/eureka
  instance:
      preferIpAddress: true
zuul:
  ignoredServices: '*'
  routes:
    hakaton-rambam-patients-service:
      path: /hakaton-rambam-patients-service/**
    hakaton-rambam-departments-service:
      path: /hakaton-rambam-departments-service/**
    hakaton-rambam-patients-assignment-service:
      path: /hakaton-rambam-patients-assignment-service/**
  host:
    socket-timeout-millis: 30000
feign:
  hystrix:
    enabled: false
    